---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
      "ssl_verify_mode": "verify_peer",
#"cookbook_path": ["/mnt/cookbooks/supermarket", "/mnt/riyic/cookbooks", "/mnt/others/cookbooks"],
      "recipe_url": "https://s3-eu-west-1.amazonaws.com/riyic/cookbooks.tar.gz",
      "cookbook_path": ["/var/chef/cookbooks", "/home/cookbooks_dev/"],
      "log_level": "debug",
  }


platforms:
  - name: riyic
    driver:
      #image: riyic_base:latest
      image: 4eixos/base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
          - /home/alambike/proxectos/chef/riyic/cookbooks:/home/cookbooks_dev:ro



suites:
  - name: default
    run_list:
        - [
            "recipe[riyic::default]", 
            "recipe[app_wordpress::deploy]",
            "recipe[riyic::test_helper]"
  ]
    attributes: {
  "app": {
    "wordpress": {
      "installation":{
            "domain": "wp.riyic.com",
            "environment": "production",
            "target_path": "/home/riyic/",
            "user": "wordpress",
            "group": "wpgrp",
            "db_name": "wpdb",
            "db_user": "wpdbuser",
            "db_host": "db",
            "db_password": "wordpress"
        }
    }
  }
}
