---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true
  socket: <%= ENV['DOCKER_HOST'] || 'tcp://172.17.42.1:4243' %>

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
      "ssl_verify_mode": "verify_peer",
      "cookbook_path": ["/home/chef_repo/vendor_cookbooks", "/home/chef_repo/cookbooks/"],
      "log_level": "debug"
  }


platforms:
  - name: riyic
    driver:
      image: 4eixos/base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
        <%= ENV['LOCAL_COOKBOOKS_PATH'] %>:/home/chef_repo:ro


suites:
  - name: default
    run_list:
        - ["recipe[riyic::default]", "recipe[app_perl::psgi_app]","recipe[riyic::test_helper]"]
    attributes: {
  "app": {
    "perl": {
      "psgi_apps": [
        {
          "domain": "perl.riyic.com",
          "environment": "test",
          "target_path": "/home/riyic/",
          "entry_point": "bin/app.pl",
          "owner": "riyic",
          "group": "riyicgrp",
          "repo_url": "https://github.com/alambike/dancer_example",
          "repo_type": "git",
          "revision": "master",
          "repo_depth": 1,
          "purge_target_path": "yes",
          "extra_modules": ["Dancer"]
        }
      ]
    }
  }
}

  - name: 'perl5-20-1'
    run_list:
      - ["recipe[riyic::default]", "recipe[app_perl::psgi_app]","recipe[app_perl::prove]","recipe[riyic::test_helper]"]
    attributes: {
  "app": {
    "perl": {
      "psgi_apps": [
        {
          "domain": "perl.riyic.com",
          "environment": "test",
          "target_path": "/home/riyic/",
          "entry_point": "bin/app.pl",
          "owner": "riyic",
          "group": "riyicgrp",
          "repo_url": "https://github.com/alambike/dancer_example",
          "repo_type": "git",
          "revision": "master",
          "repo_depth": 1,
          "purge_target_path": "yes",
          "extra_modules": ["Dancer"]
        }
      ]
    }
  },
  "lang": {
      "perl":{
          "version": "perl-5.20.1"
      }
  }

}
