---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
      "ssl_verify_mode": "verify_peer",
      "cookbook_path": ["/mnt/cookbooks/supermarket", "/mnt/riyic/cookbooks", "/mnt/others/cookbooks"],
      "log_level": "debug"
  }


platforms:
  - name: riyic
    driver:
      image: riyic_base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
          - /opt/chef:/opt/chef:ro
          - /home/alambike/proxectos/chef:/mnt/:ro



suites:
  - name: default
    run_list:
        - [
            "recipe[riyic::default]", 
            "recipe[app_phplist::deploy]",
            "recipe[riyic::test_helper]"
  ]
    attributes: {
  "app": {
    "phplist": {
      "installations": [
        {
            "domain": "phplist.riyic.com",
            "environment": "production",
            "target_path": "/home/riyic/",
            "user": "phplist",
            "group": "riyicgrp",
            'db_name': 'phplist',
            'db_user': 'phplist',
            'db_host': 'db',
            'db_password': 'phplist',
            'smtp_user': 'test_user',
            'smtp_password': 'password',
            'smtp_server': 'mail.test.com',
            'test_mode': 0,
            'bounce_address': 'bounces@phplist.riyic.com',
            'bounce_mailbox_host': 'pop3_host.riyic.com',
            'bounce_mailbox_user' : 'username',
            'bounce_mailbox_password': 'password',
            'bounce_unsuscribe_threshold' : 5
        }
      ]
    }
  }
}
