---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true
  socket: <%= ENV['DOCKER_HOST'] || 'tcp://172.17.42.1:4243' %>

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
    "ssl_verify_mode": "verify_peer",
    "log_level": "debug",
    "cookbook_path": ["/home/chef_repo/vendor_cookbooks", "/home/chef_repo/cookbooks/"],
  }


platforms:
  - name: riyic
    driver:
      image: 4eixos/base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
        <%= ENV['LOCAL_COOKBOOKS_PATH'] %>:/home/chef_repo:ro



suites:
  - name: default
    run_list:
        - [
            "recipe[riyic::default]", 
            "recipe[dbs_mongodb::default]", 
            "recipe[riyic::test_helper]"
    ]
    attributes: {
    "dbs": {
        "mongodb": {
          "server": {
          },
          "dbs": [
            {
              "name": "test_db",
              "user": "test_user",
              "password": "b4uNGag"
            }
          ],
        }
    }
}
