---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true
  socket: <%= ENV['DOCKER_HOST'] || 'tcp://172.17.42.1:4243' %>

provisioner:
  name: chef_solo
  solo_rb: {
    "ssl_verify_mode": "verify_peer",
    "cookbook_path": ["/home/chef_repo/vendor_cookbooks", "/home/chef_repo/cookbooks/"],
    "log_level": "debug",
  }


platforms:
  - name: riyic
    driver:
      image: 4eixos/base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
        <%= ENV['LOCAL_COOKBOOKS_PATH'] %>:/home/chef_repo:ro



suites:
  - name: default
    run_list:
      - [
          "recipe[riyic::default]", 
          "recipe[appserver_nginx::default]",
          "recipe[riyic::test_helper]"
  ]
    attributes: {}
  - name: package
    run_list:
      - [
          "recipe[riyic::default]", 
          "recipe[appserver_nginx::package]",
          "recipe[riyic::test_helper]"
      ]
    attributes: {}
