---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
      "ssl_verify_mode": "verify_peer",
      "cookbook_path": ["/mnt/cookbooks/supermarket", "/mnt/riyic/cookbooks", "/mnt/others/cookbooks"],
      "log_level": "debug"
  }


platforms:
  - name: riyic
    driver:
      image: riyic_base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
          - /opt/chef:/opt/chef:ro
          - /home/alambike/proxectos/chef:/mnt/:ro



suites:
  - name: default
    run_list:
        - ["recipe[riyic::default]", "recipe[app_php::fcgi_app]"]
    attributes: {
  "riyic": {
    "dockerized": "yes",
    "updates_check_interval": "never"
  },
  "app": {
    "php": {
      "fcgi_apps": [
        {
          "domain": "wp.riyic.com",
          "environment": "production",
          "target_path": "/home/riyic/",
          "owner": "riyic",
          "repo_url": "https://github.com/WordPress/WordPress.git",
          "repo_type": "git",
          "migrate": "no",
          "group": "riyicgrp",
          "revision": "4.0.1",
          "repo_depth": 1,
          "purge_target_path": "yes"
        }
      ]
    }
  }
}
