---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
      "ssl_verify_mode": "verify_peer",
      "cookbook_path": ["/mnt/cookbooks/supermarket", "/mnt/riyic/cookbooks", "/mnt/others/cookbooks"],
      "log_level": "debug"
  }


platforms:
  - name: riyic
    driver:
      image: riyic_base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
          - /opt/chef:/opt/chef:ro
          - /home/alambike/proxectos/chef:/mnt/:ro



suites:
  - name: default
    run_list:
        - [
            "recipe[riyic::default]", 
            "recipe[system_user::with_lshell]",
            "recipe[riyic::test_helper]"
  ]
    attributes: {
        "system":{
                "users": {
                        "lshell": [
                                {
                                        "username": "user1",
                                        "password": "user1",
                                        "group": "users",
                                        "shell_options": {
                                                "intro" : "== Cloud ==\nWelcome to shell\nType '?' or 'help' to get the list of allowed commands",
                                                "path" : ["/home/user1"]
                                        }
                                }
                        ]
                }
        }
}
