default["mq"]["zeromq"]["download_dir"] = "/opt/zeromq"
default["mq"]["zeromq"]["install_dir"] = "/usr/local"
default["mq"]["zeromq"]["download_url"] = "http://download.zeromq.org"
default["mq"]["zeromq"]["version"] = "4.0.3"
default["mq"]["zeromq"]["force_recompile"] = "no"
