---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
      "ssl_verify_mode": "verify_peer",
      "cookbook_path": ["/var/supermarket", "/var/cookbooks"],
      "log_level": "debug"
  }

platforms:
  - name: minecraftserver
    driver:
      image: 4eixos/base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
          - /home/cookbooks:/var/cookbooks:ro
          - /home/supermarket:/var/supermarket:ro

suites:
  - name: default
    run_list: [
            "recipe[riyic::default]","recipe[app_minecraft::default]","recipe[riyic::test_helper]"]
    attributes: {
	  "lang" : {
	     "java" : {
	       "install_flavor": "oracle",
	       "jdk_version" : "7",
	       #"java_home" : "/opt/java/",
	       "oracle" : {"accept_oracle_download_terms" : true}
	   }
	   },
	
	  "app" : {
	     "minecraft" : {
	       "opname" : "admin",
	       "online-mode" : "false",
	       "monsters" : "true",
	       "server-port" : "25565",
	       "max-players" : "20",
	       "level-name" : "world"
	   }
	   },
    }
