default["riyic"]["system_locale"] = 'es_ES.UTF-8'
#default["riyic"]["system_timezone"] = 'Etc/UTC'
default["riyic"]["system_timezone"] = 'Europe/Madrid'
default["riyic"]["enable_report"] = 'no'
default["riyic"]["updates_check_interval"] = 'never'
default['riyic']['install_runit_inside_container'] = 'yes'
