---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true
  socket: <%= ENV['DOCKER_HOST'] || 'tcp://172.17.42.1:4243' %>

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
    "ssl_verify_mode": "verify_peer",
    "cookbook_path": ["/home/chef_repo/vendor_cookbooks", "/home/chef_repo/cookbooks/"],
    "log_level": "debug"
  }


platforms:
  - name: 14.04
    driver:
      image: ubuntu:14.04
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
        <%= ENV['LOCAL_COOKBOOKS_PATH'] %>:/home/chef_repo:ro
      volumes_from:
        - chef


suites:
  - name: default
    run_list:
        - [
            "recipe[riyic::default]",
            "recipe[app_odoo::deploy]",
            "recipe[riyic::test_helper]"
  ]
    attributes: {
  "app": {
    "odoo": {
      "installations": [
        {
          "domain": "odoo.riyic.com",
          "target_path": "/opt/odoo/",
          "entry_point": "openerp-wsgi.py",
          "owner": "odoo",
          "group": "odoogrp",
          "admin_password": "testing",
          "data_dir": "/opt/odoo/data",
          "db_user": "odoo_db",
          "db_name": "odoo_user",
          "db_password": "odoo_pass"
        }
      ]
    }
  }
}
  - name: completa
    run_list:
      - [
        "recipe[riyic::default]",
        "recipe[dbs_postgresql::server]",
        "recipe[dbs_postgresql::create_db]",
        "recipe[dbs_postgresql::user_extra_privileges]",
        "recipe[app_odoo::deploy]",
        "recipe[riyic::test_helper]"
    ]
    attributes: {
  "app": {
    "odoo": {
      "installations": [
        {
          "domain": "odoo.riyic.com",
          "target_path": "/opt/odoo/",
          "entry_point": "openerp-wsgi.py",
          "owner": "odoo",
          "group": "odoogrp",
          "admin_password": "testing",
          "data_dir": "/opt/odoo/data",
          "db_host": "localhost",
          "db_user": "odoo_user",
          "db_name": "odoo_db",
          "db_password": "odoo_pass"
        }
      ]
    }
  },
  "dbs": {
      "postgresql": {
        "server": {
          "postgres_password": "bcA3w",
          "allow_remote_connections": "yes"
        },
        "dbs": [
          {
            "name": "odoo_db",
            "user": "odoo_user",
            "password": "odoo_pass"
          }
        ],
        "user_extra_options": [
          {
            "user": "odoo_user",
            "extra_privileges": [
              "CREATEDB"
            ],
            "allow_remote_connections": "yes"
          }
        ]
      }
  }
}

  - name: completa8
    run_list:
      - [
        "recipe[riyic::default]",
        "recipe[dbs_postgresql::server]",
        "recipe[dbs_postgresql::create_db]",
        "recipe[dbs_postgresql::user_extra_privileges]",
        "recipe[app_odoo::deploy]",
        "recipe[riyic::test_helper]"
    ]
    attributes: {
  "app": {
    "odoo": {
      "installations": [
        {
          "domain": "odoo.riyic.com",
          "target_path": "/opt/odoo/",
          "entry_point": "openerp-wsgi.py",
          "owner": "odoo",
          "group": "odoogrp",
          "admin_password": "testing",
          "data_dir": "/opt/odoo/data",
          "db_user": "odoo_user",
          "db_host": "localhost",
          "db_name": "odoo_db",
          "db_password": "odoo_pass",
          "version": "8.0"
        }
      ]
    }
  },
  "dbs": {
      "postgresql": {
        "server": {
          "postgres_password": "bcA3w",
          "allow_remote_connections": "yes"
        },
        "dbs": [
          {
            "name": "odoo_db",
            "user": "odoo_user",
            "password": "odoo_pass"
          }
        ],
        "user_extra_options": [
          {
            "user": "odoo_user",
            "extra_privileges": [
              "CREATEDB"
            ],
            "allow_remote_connections": "yes"
          }
        ]
      }
  }
}
