---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true
  socket: <%= ENV['DOCKER_HOST'] || 'tcp://172.17.42.1:4243' %>

provisioner:
  name: chef_solo
  #chef_omnibus_root: /opt/chef/
  solo_rb: {
      "ssl_verify_mode": "verify_peer",
      "log_level": "debug",
      "cookbook_path": ["/home/chef_repo/vendor_cookbooks", "/home/chef_repo/cookbooks/"]
  }


platforms:
  - name: 14.04
    driver:
      image: ubuntu:14.04
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
        - <%= ENV['LOCAL_COOKBOOKS_PATH'] %>:/home/chef_repo:ro
      volumes_from:
        - chef

  - name: 16.04
    driver:
      image: ubuntu:16.04
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
        - <%= ENV['LOCAL_COOKBOOKS_PATH'] %>:/home/chef_repo:ro
      volumes_from:
        - chef


suites:
  - name: default
    run_list:
        - [
            "recipe[riyic::default]", 
            "recipe[dbs_mysql::server]", 
            "recipe[dbs_mysql::create_db]", 
            "recipe[riyic::test_helper]"
    ]
    attributes: {
    "dbs": {
        "mysql": {
          "server": {
            "root_password": "mypassword",
            #"repl_password": "mypassword",
            #"debian_password": "mypassword",
            "bind_address": "0.0.0.0",
          },
          "dbs": [
            {
              "name": "test_db",
              "user": "test_user",
              "password": "b4uNGag"
            }
          ],
        }
    }
}
