---
driver:
  name: docker
  use_sudo: false
  disable_upstart: false
  remove_images: true
  socket: <%= ENV['DOCKER_HOST'] || 'tcp://172.17.42.1:4243' %>

provisioner:
  name: chef_solo
  solo_rb: {
      "ssl_verify_mode": "verify_peer",
      "recipe_url": "https://s3-eu-west-1.amazonaws.com/riyic/cookbooks.tar.gz",
      "cookbook_path": ["/var/chef/cookbooks", "/home/cookbooks"],
      "log_level": "debug",
  }


platforms:
  - name: prefapp
    driver:
      image: 4eixos/base:latest
      platform: ubuntu
      require_chef_omnibus: false
      use_cache: false
      remove_images: false
      volume:
          - <%= ENV['LOCAL_COOKBOOKS_PATH'] %>:/home/cookbooks:ro



suites:
  - name: default
    run_list:
        - [
            "recipe[riyic::default]", 
            "recipe[app_moodle::deploy]",
            "recipe[riyic::test_helper]"
  ]
    attributes: {
  "app": {
    "moodle": {
      "installation":{
            "domain": "wp.riyic.com",
            "environment": "production",
            "target_path": "/home/riyic/",
            "user": "wordpress",
            "group": "wpgrp",
            "db_name": "wpdb",
            "db_user": "wpdbuser",
            "db_host": "db",
            "db_password": "wordpress"
        }
    }
  }
}
